### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by Vistaus** [danilocodes/brightness-control-wayland#1]
Thank you for creating this tool! I was so waiting for a screen brightness controller on Wayland!

However, I get an error during executing:

```
~ ./brightness +10
error: Found argument 'adjust' which wasn't expected, or isn't valid in this context

USAGE:
    gnome-randr [SUBCOMMAND]

For more information try --help
error: Found argument 'adjust' which wasn't expected, or isn't valid in this context

USAGE:
    gnome-randr [SUBCOMMAND]

For more information try --help
error: Found argument 'adjust' which wasn't expected, or isn't valid in this context

USAGE:
    gnome-randr [SUBCOMMAND]

For more information try --help
```

**Comment by danilocodes** [comment]
I never expected anyone to use this other than me, I created this when I moved from xorg to wayland and my previous script stopped working, I'll take a look tomorrow.

**Comment by danilocodes** [comment]
I have not been able to reproduce this behavior on my system, can you provide me with your version of gnome-randr?

**Comment by Vistaus** [comment]
Thanks for looking into it!

gnome-randr 0.1.1

**Comment by danilocodes** [comment]
Same version I'm using, but I have an idea of ​​what it could be and I need to do some tests

**Comment by Vistaus** [comment]
That's great! Thanks again for looking into it! 🙂

**Comment by danilocodes** [comment]
ok I have a possible fix, I didn't remember this earlier because I only had to tinker with it once to get it to work.

`gnome-randr` doesn't support this by default, it's in a separate experimental branch for this [issue](https://github.com/maxwellainatchi/gnome-randr-rust/issues/16)
(my fault for not documenting this in the README)

Here is how to fix:

```bash
git clone https://github.com/maxwellainatchi/gnome-randr-rust.git
cd gnome-randr-rust/
git fetch
git checkout adjust-brightness 
cargo install .
cargo build

sudo apt install libdbus-1-dev pkg-config # NOTE run this if cargo build fails
```

you can quickly test by:
```bash
cd target/debug/
./gnome-randr adjust HDMI-1 --brightness 0.5
# NOTE run ./gnome-randr without any argument to get the list of your displays (HDMI-1 for me)
```

after that, just copy it to somewhere in your PATH and `brightness-control-wayland` should be working:

```bash
sudo cp gnome-randr /usr/local/bin/
```

**Comment by Vistaus** [comment]
Thank you for the instructions! However, I still can't get it to work. And I realize it's partly my fault too, as I didn't give enough details. I'm using openSUSE Tumbleweed with KDE Plasma 5.27.2

```
./gnome-randr adjust HDMI-1 --brightness 0.5
The name org.gnome.Mutter.DisplayConfig was not provided by any .service files
```

But it looks like it's only looking for Mutter, so I'm guessing it's not going to work with KWin? :(
